### ISSUE TITLE
FOUNDATIONS: Setting Branch Name

### ISSUE THREAD

**Issue by mabroukmahdhi** [cjdutoit/Standardly#120]
Why the branche name mentions only the last actions, for example when creating a controller:
![image](https://user-images.githubusercontent.com/16063715/198854094-ad3419f9-3350-48a9-9d41-f83f158fe355.png)

**Comment by cjdutoit** [comment]
Each action had its own PR.   You will see seperate PR's for `GET` `POST` `PUT` `DELETE`

**Comment by mabroukmahdhi** [comment]
Great :D
