### ISSUE TITLE
Error when running Unit and Acceptance test

### ISSUE THREAD

**Issue by marthinkondjeni** [cjdutoit/Standardly#123]
Whenever I am running my Unit test, I am getting this error

Message: 
System.TypeInitializationException : The type initializer for 'SystemEnterprise.Api.Models.Employees.Employee' threw an exception.
---- System.Exception : The type [Employee] was not registered in the randomizer.

**Comment by cjdutoit** [comment]
@marthinkondjeni I can't reproduce this error.  Can you provide more details?

**Comment by mabroukmahdhi** [comment]
I guess the model is not created or you need to add a reference to your test project.

**Comment by cjdutoit** [comment]
`Tynamix.ObjectFiller` has some logic that will ignore classes that starts with `System` or `Microsoft`

If the namespaces is cahnged the issue will be resolved.  

```cs
private static bool TypeIsPoco(Type type)
{
    return !type.IsValueType() && !type.IsArray && type.IsClass() && type.GetProperties(false).Any()
      && (type.Namespace == null
        || (!type.Namespace.StartsWith("System") && !type.Namespace.StartsWith("Microsoft")));
}
```
