### ISSUE TITLE
MINORFIX: Fixing Owner Name in License file.

### ISSUE THREAD

**Issue by mabroukmahdhi** [cjdutoit/Standardly#50]
When the project is created, using the template, the license text is starting with:

**ADotNet - .NET Library

Copyright (c) 2021 Hassan Habib All rights reserved.**

**Comment by cjdutoit** [comment]
Hi @mabroukmahdhi, we can close this one.  When you install ADotNet, that Licence file gets added to the root of that project automatically.  This is by design.

**Comment by mabroukmahdhi** [comment]
Okay, I close this issue.
