### ISSUE TITLE
TEMPLATES: Adding a template for Azure Functions Project

### ISSUE THREAD

**Issue by mabroukmahdhi** [cjdutoit/Standardly#71]
I am working on an Azure Functions Project and I would like to have a template for it.. Let's do it 😍

**Comment by cjdutoit** [comment]
Hi @mabroukmahdhi,

I think what Visual Studio offer out of the box is superior to what we can offer through standardly as you can select and configure your triggers via the UI.

![image](https://user-images.githubusercontent.com/797750/186925547-0aac6aaf-c960-4565-b201-970f872795a4.png)
