### ISSUE TITLE
TEMPLATES: Add Template For Relational Entities W/ Composite Key As ID

### ISSUE THREAD

**Issue by Spectralgo** [cjdutoit/Standardly#72]
@cjdutoit How should we tackle this ?

**Comment by coeur85** [comment]
i think u need to build relations manual after generating the model.

**Comment by Spectralgo** [comment]
@coeur85 this is not the issue.

The problem is with the TDD structural validation of the ID

**Comment by coeur85** [comment]
can you elaborate with an example ?

**Comment by Spectralgo** [comment]
![SmartSelect_20220731-200604_GitHub.jpg](https://user-images.githubusercontent.com/56794425/182035219-662ac640-e0c3-4a1b-bfd4-ba1e1e981292.jpg)

There's no template to build a realtional entity like this one.

The TDD would be built on a single guid ID.

I guess you can Code Rub it after and delete the single ID and just keep the relational ones.

Now that I think about it. The work to add this feature might not be worth it.

**Comment by coeur85** [comment]
:) my point exactly.
because it's more tied to the business logic. and not that common for normal scenarios.

**Comment by coeur85** [comment]
@cjdutoit
