### ISSUE TITLE
The state of checkbox's configurations is not saved

### ISSUE THREAD

**Issue by Spectralgo** [cjdutoit/Standardly#73]
![image](https://user-images.githubusercontent.com/56794425/182130442-3ab4c792-1b03-455b-95ea-3e2ff32df0e4.png)

Doesn't save previous state, it's reverting to "checked" state each time.

**Comment by cjdutoit** [comment]
@Spectralgo this is by design.  You can change the state under options.  This is just to allow you to do a one time override of the settings.  On opening the form it will revert back to what you save under settings.
