### ISSUE TITLE
New Feature: Ignore Properties Dynamically On Test Filler 

### ISSUE THREAD

**Issue by Spectralgo** [cjdutoit/Standardly#74]
![image](https://user-images.githubusercontent.com/56794425/183990909-4600f9e9-9787-43e3-9516-3048169c09b2.png)

It would be nice to have this todo replaced by an input cell in the generator form. It would help preserve TDD with existing relationships.

I can do it manually by editing the template, but it would be a nice feature to keep the template clean.

**Comment by coeur85** [comment]
can you share the template ?

**Comment by Spectralgo** [comment]
You're not changing just one file, you have to change every template called for the test setup.

You replace the Todo by:

.On property (x => x.YOURPROP ) . IgnoreIt()
.On property (x => x.YOURPROP ) . IgnoreIt();

I do a find and replace targeting this Todo in all foundation templates before scaffolding.

You also need to take care of the semicolon to chain statements properly

Florian Renard
________________________________

**Comment by cjdutoit** [comment]
@Spectralgo at the moment we are not considering a model builder for the entities.

Just like you would need to update the configurations on the storage broker, you will also need to manually amend the filler to exclude navigation properties and also how certain datatypes need to be handles i.e. DateOnly etc. so it is not always a case of just the navigation properties.
